#!/usr/bin/env python3
# -*- mode: python -*-
#
# Copyright (c) 2020 The Atomic Swap Network Developers
# Licensed under the GNU General Public License, Version 3.

import asyncio
import sys
import os

from asns import asns_api, get_path


if __name__ == '__main__':
    argv = sys.argv
    get_path()

    base_path = None
    if len(argv) == 2:
        if argv[1].startswith("--base_path="):
            base_path = os.path.expanduser(argv[1][12:])
            if not os.path.isdir(os.path.split(base_path)[0]):
                raise Exception("The specified folder can't be created.")
    asns_api.db_base_path = base_path
    loop = asyncio.get_event_loop()
    gather = asyncio.gather(
        asns_api.run()
    )
    loop.run_until_complete(gather)
