#!/usr/bin/env python3
# -*- mode: python -*-
#
# Copyright (c) 2020 The Atomic Swap Network Developers
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import asyncio
import sys
import os

from asns import asns_api, get_path


if __name__ == '__main__':
    argv = sys.argv
    get_path()

    base_path = None
    if len(argv) == 2:
        if argv[1].startswith("--base_path="):
            base_path = os.path.expanduser(argv[1][12:])
            if not os.path.isdir(os.path.split(base_path)[0]):
                raise Exception("The specified folder can't be created.")
    asns_api.db_base_path = base_path
    loop = asyncio.get_event_loop()
    gather = asyncio.gather(
        asns_api.run()
    )
    loop.run_until_complete(gather)
